### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by muradilqarli** [ilhamridho04/get-contact.js#1]
hi, i have 2 problem, please help me

node example.js
/home/cyberman/test/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
[428814:428814:1102/115713.957128:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[428814:428814:1102/115713.957158:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/cyberman/test/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at ChildProcess.<anonymous> (/home/cyberman/test/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:232:79)
    at ChildProcess.emit (node:events:526:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

Node.js v18.17.1

================================================

npm i getcontact-web.js

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/getcontact-web.js - Not found
npm ERR! 404
npm ERR! 404  'getcontact-web.js@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /home/cyberman/.npm/_logs/2023-11-02T11_58_56_984Z-debug-0.log

**Comment by ilhamridho04** [comment]
try `headless: true`

**Comment by ilhamridho04** [comment]
https://www.npmjs.com/package/get-contact.js

**Comment by muradilqarli** [comment]
my os - ubuntu 22.04 (LTS)

node --version
 - v18.17.1
 - 
 npm --version
 10.2.2
 
 ========================

command

1) npm i get-contact.js

2) npm install puppeteer

3) nano example.js

````
const { GClient } = require("get-contact.js");

const gclient = new GClient();

gclient.on("qr", (qr) => {
  // Generate and scan this code with your phone
  console.log("QR RECEIVED", qr);
});

gclient.on("ready", () => {
  console.log("Client is ready!");
});

gclient.initialize();
```

next node example.js


```
node example.js
/home/cyberman/test/node_modules/get-contact.js/src/GClient.js:51
    this.authStrategy.setup(this);
                      ^

TypeError: Cannot read properties of undefined (reading 'setup')
    at new GClient (/home/cyberman/test/node_modules/get-contact.js/src/GClient.js:51:23)
    at Object.<anonymous> (/home/cyberman/test/example.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.1

```

**Comment by muradilqarli** [comment]
hi my friend, first of all thanks a lot for your reply. I did the steps above and then it gave me an error and I guess I didn't do the right steps. Could you please tell me the correct commands in sequence

**Comment by muradilqarli** [comment]
> try `headless: true`

i dont understand this

**Comment by ilhamridho04** [comment]
edit test/searchNumber.test.js
`puppeteer: {
    // args: ['--proxy-server=proxy-server-that-requires-authentication.example.com'],
    headless: false,
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-accelerated-2d-canvas",
      "--no-first-run",
      "--no-zygote",
      "--single-process", // <- this one doesn't works in Windows
      "--disable-gpu",
    ],
  },`
  
run `npm test`

**Comment by ilhamridho04** [comment]
![image](https://github.com/ilhamridho04/get-contact.js/assets/45212532/623a7044-c13e-4171-bbef-d3704117a857)

**Comment by muradilqarli** [comment]
npm test

> get-contact.js@1.8.3 test
> nodemon ./test/searchNumber.test.js

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node ./test/searchNumber.test.js`
/home/cyberman/test/get-contact.js/test/searchNumber.test.js:13
  authStrategy: new GLocalAuth({
              ^

SyntaxError: Unexpected token ':'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.1
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ilhamridho04** [comment]
> > try `headless: true`
> 
> i dont understand this

if your OS support GUI `headless: false` is work, if your OS not GUI use this `headless: true`

**Comment by muradilqarli** [comment]
i can changed this file.

```
const { GClient, GLocalAuth } = require("../index");
const qrcode = require("qrcode-terminal");
const readline = require("readline");

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const client = new GClient({
  // proxyAuthentication: { username: 'username', password: 'password' },
  puppeteer: { headless: false, args: [ "--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--disable-accelerated-2d-canvas", "--no-first-run", "--no-zygote", "--single-process", // <- this one doesn't works in Windows "--disable-gpu", ], },
  authStrategy: new GLocalAuth({
    clientId: "test-aja-inimah",
    // dataPath: './.gwebjs_auth/'
  }),
});

client.initialize();

client.on("qr", (qr) => {
  // NOTE: This event will not be fired if a session is specified.
  console.log("QR RECEIVED", qr);
  qrcode.generate(qr, { small: true });
});

client.on("authenticated", async () => {
  console.log("AUTHENTICATED");
  // client.searchNumber("ID", "085771116774").then((result) => {
  //   console.log(result);
  // });
});

client.on("ready", () => {
  console.log("READY");
  hitung();
});

function hitung() {
  rl.question("Masukan nomor: ", (nomor) => {
    client.searchNumber("ID", nomor).then((result) => {
      console.log(result);
    });

    rl.question("Ingin melakukan pencarian lagi? (y/n) ", (jawaban) => {
      if (jawaban.toLowerCase() === "y") {
        hitung();
      } else {
        rl.close();
      }
    });
  });
}


```

**Comment by muradilqarli** [comment]
> > > try `headless: true`
> > 
> > 
> > i dont understand this
> 
> if your OS support GUI `headless: false` is work, if your OS not GUI use this `headless: true`

I am using this tool on an external server. I didn't quite understand where to change `headless: true'

**Comment by ilhamridho04** [comment]
const client = new GClient({
puppeteer: {
headless: true, // <- you can change it here
args: [
"--no-sandbox",
"--disable-setuid-sandbox",
"--disable-dev-shm-usage",
"--disable-accelerated-2d-canvas",
"--no-first-run",
"--no-zygote",
"--single-process", // <- this one doesn't works in Windows
"--disable-gpu",
],
},
authStrategy: new GLocalAuth({
clientId: "test-aja-inimah",
}),
});

**Comment by ilhamridho04** [comment]
thi example for my external server

Ubuntu 20.04.6 LTS
node v18.18.2
npm 9.8.1

`console.log(`Sesi gclient (${sesi.id}) tidak aktif.`);
          console.log(`Sedang membuat sesi : ${sesi.id}`);
          const fileGClient = `${sesi.id}.json`;
          const filePatchGclient = path.join(getContactPath, fileGClient);
          gclient = new GClient({
            restartOnAuthFail: true,
            puppeteer: {
              headless: true,
              args: [
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",
                "--disable-accelerated-2d-canvas",
                "--no-first-run",
                "--no-zygote",
                "--single-process", // <- this one doesn't works in Windows
                "--disable-gpu",
              ],
            },
            authStrategy: new GLocalAuth({
              clientId: sesi.id,
              // dataPath: './.gwebjs_auth/'
            }),
          });

          gclient.initialize();

          gclient.on("qr", async (qr) => {
            console.log(
              "==============================================\nQR RECEIVED for " +
              sesi.name +
              " :\n" +
              qr +
              "\n==============================================\n"
            );
            qrcode.toDataURL(qr, (err, url) => {
              io.emit("gc-qr", { id: sesi.id, src: url });
              io.emit("gc-message", {
                id: sesi.id,
                text: "QR Code received, scan please!",
              });
            });
            const updateSessionData = {
              pic: 'assets/dist/img/avatar-default.jpg',
              ready: false
            }

            await getContactSessionModel.updateSessionReady(sesi.users_id, updateSessionData, (err, result) => {
              if (err) {
                console.error('Gagal memperbarui sesi:', err);
                return;
              }
              console.log(`Sesi berhasil diperbarui menjadi : ${JSON.stringify(result)}`);
            });
            deleteJsonFile(filePatchGclient);
          });

          gclient.on("ready", async () => {
            io.emit("gc-ready", { id: sesi.id });
            io.emit("gc-message", { id: sesi.id, text: "GetContact is ready!" });
            io.emit("gc-toast", { status: 'success', message: "GetContact telah ready." });
            const savedSessions = {
              id: sesi.id,
              name: sesi.name,
              description: sesi.description,
              ready: true,
              users_id: sesi.users_id,
              gclient: gclient,
            };
            saveGetContactJson(savedSessions, sesi.id);
            const sessionIndex = gcClient.findIndex((sess) => sess.id == sesi.id);
            if (sessionIndex == -1) {
              gcClient.push({
                id: sesi.id,
                name: sesi.name,
                gclient: gclient,
              });
              console.log(`Sessions ${sesi.name} telah ditambahkan.`);
            }
            const updateSessionData = {
              pic: 'assets/dist/img/avatar-default.jpg',
              ready: true
            }

            await getContactSessionModel.updateSessionReady(sesi.users_id, updateSessionData, (err, result) => {
              if (err) {
                console.error('Gagal memperbarui sesi:', err);
                return;
              }
              console.log(`Sesi berhasil diperbarui menjadi : ${JSON.stringify(result)}`);
            });
          });

          gclient.on("authenticated", () => {
            io.emit("gc-authenticated", { id: sesi.id });
            io.emit("gc-message", { id: sesi.id, text: "GetContact is authenticated!" });
            console.log("GetContact " + sesi.name + " is authenticated!");
          });

          io.on("connection", function (socket) {
            socket.emit("gc-init", sesi);
          });

          res.render("getcontact/getcontact", {
            title: "GetContact",
            menu: "getcontact",
            menuItem: "",
            user: user,
            getcontactData: sessData[0],
            dataTable: false,
            foto: sesi.pic,
            csrfToken: csrfToken
          });
        }`

**Comment by muradilqarli** [comment]
Thank you very much for your help.
